/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
 
export function AngryV2(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/models/RevisedV2/Angry.gltf");
    const { actions,names } = useAnimations(animations, group);

    useEffect(()=>{
      console.log(actions)
      console.log(names)
      actions[names[0]].reset().fadeIn(0.5).play()
    },[])
    return (
      <group ref={group} {...props} dispose={null} scale = {0.01}>
        <group>
        <group name="Angry" position={[0.121, -153.287, 10.379]}>
        <group
            name="Tail"
            position={[-0.121, 42.287, -10.379]}
            rotation={[0, 0.401, 0]}
          >
            <skinnedMesh
              name="Tail_1"
              geometry={nodes.Tail_1.geometry}
              material={materials["Mat.1"]}
              skeleton={nodes.Tail_1.skeleton}
            />
          </group>
          <mesh
            name="Angryai"
            castShadow
            receiveShadow
            geometry={nodes.Angryai.geometry}
            material={materials["Mat.2"]}
            position={[-272.994, 86.765, -10.379]}
          />
          <group name="Legs" position={[0.603, 263.139, -10.379]}>
            <skinnedMesh
              name="Legs_1"
              geometry={nodes.Legs_1.geometry}
              material={materials["Mat.1"]}
              skeleton={nodes.Legs_1.skeleton}
            />
          </group>
          <group name="Null" position={[-0.121, 23.265, -10.379]}>
            <primitive object={nodes.Joint2} />
            <primitive object={nodes.AngryHip_R} />
            <primitive object={nodes.AngryHip_L} />
            <mesh
              name="Body"
              castShadow
              receiveShadow
              geometry={nodes.Body.geometry}
              material={materials["Mat.1"]}
              morphTargetDictionary={nodes.Body.morphTargetDictionary}
              morphTargetInfluences={nodes.Body.morphTargetInfluences}
              position={[0, 58.68, 9.654]}
              scale={100}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/RevisedV2/Angry.gltf");
