/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
 
export function FearV2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/RevisedV2/Fear.gltf");
  const { actions,names } = useAnimations(animations, group);

  useEffect(()=>{
    console.log(actions)
    console.log(names)
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])
  return (
    <group ref={group} {...props} dispose={null} scale={0.01}>
        <group>
        <group name="Fear" position={[-6.762, -120.176, 46.938]}>
          <mesh
            name="scaredai"
            castShadow
            receiveShadow
            geometry={nodes.scaredai.geometry}
            material={materials["Mat.2"]}
            position={[-257.516, -186.18, -46.938]}
          />
          <mesh
            name="FearParticle1"
            castShadow
            receiveShadow
            geometry={nodes.FearParticle1.geometry}
            material={materials["Mat.1"]}
            position={[89.797, 76.937, -46.1]}
            rotation={[0, -0.023, -1.134]}
            scale={1.166}
          />
          <mesh
            name="FearParticle"
            castShadow
            receiveShadow
            geometry={nodes.FearParticle.geometry}
            material={materials["Mat.1"]}
            position={[-42.534, 71.745, -48.047]}
          />
          <mesh
            name="Mouth"
            castShadow
            receiveShadow
            geometry={nodes.Mouth.geometry}
            
            position={[-4.622, -54.051, 36.494]}
            rotation={[-0.195, 0, 0]}
           ><meshStandardMaterial color={"#F5F5F5"}/></mesh>
          <mesh
            name="Eye"
            castShadow
            receiveShadow
            geometry={nodes.Eye.geometry}
            material={materials["Mat.2"]}
            position={[2.817, -23.338, 23.163]}
            rotation={[-0.183, 0, -0.017]}
           ><meshStandardMaterial color={"#F5F5F5"}/></mesh>
          <mesh
            name="Body"
            castShadow
            receiveShadow
            geometry={nodes.Body.geometry}
            material={materials["Mat.1"]}
            morphTargetDictionary={nodes.Body.morphTargetDictionary}
            morphTargetInfluences={nodes.Body.morphTargetInfluences}
            position={[11.227, -143.311, -51.248]}
            scale={20}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/RevisedV2/Fear.gltf");