/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
 
export function HappyV2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/RevisedV2/Happy.gltf");
  const { actions,names } = useAnimations(animations, group);
  useEffect(()=>{
    console.log(actions)
    console.log(names)
    actions[names[0]].reset().fadeIn().play()
  },[])
  return (
    <group ref={group} {...props} dispose={null} scale={0.01}>
      <group>
        <group name="Happy" position={[0.685,-100.287, 41.707]} >
          <group
            name="Null5"
            position={[-0.685, 92.414, -41.707]}
            rotation={[0, 0, -0.885]}
          >
            <mesh
              name="Particle"
              castShadow
              receiveShadow
              geometry={nodes.Particle.geometry}
              material={materials["Mat.1"]}
              position={[0, 205.63, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={0}
            />
          </group>
          <group
            name="Null4"
            position={[-0.685, 92.414, -41.707]}
            rotation={[0, 0, -1.396]}
          >
            <mesh
              name="Particle_1"
              castShadow
              receiveShadow
              geometry={nodes.Particle_1.geometry}
              material={materials["Mat.1"]}
              position={[0, 205.63, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={0}
            />
          </group>
          <group
            name="Null3"
            position={[-0.685, 92.414, -41.707]}
            rotation={[0, 0, -1.833]}
          >
            <mesh
              name="Particle_2"
              castShadow
              receiveShadow
              geometry={nodes.Particle_2.geometry}
              material={materials["Mat.1"]}
              position={[0, 205.63, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={0}
            />
          </group>
          <group
            name="Null2"
            position={[-0.685, 92.414, -41.707]}
            rotation={[0, 0, 1.396]}
          >
            <mesh
              name="Particle_3"
              castShadow
              receiveShadow
              geometry={nodes.Particle_3.geometry}
              material={materials["Mat.1"]}
              position={[0, 205.63, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={0}
            />
          </group>
          <group
            name="Null1"
            position={[-0.685, 92.414, -41.707]}
            rotation={[0, 0, 0.873]}
          >
            <mesh
              name="Particle_4"
              castShadow
              receiveShadow
              geometry={nodes.Particle_4.geometry}
              material={materials["Mat.1"]}
              position={[0, 205.63, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={0}
            />
          </group>
          <group
            name="Null"
            position={[-0.685, 92.414, -41.707]}
            rotation={[0, 0, 1.833]}
          >
            <mesh
              name="Particle1"
              castShadow
              receiveShadow
              geometry={nodes.Particle1.geometry}
              material={materials["Mat.1"]}
              position={[0, 205.63, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={0}
            />
          </group>
          <mesh
            name="Happyai"
            castShadow
            receiveShadow
            geometry={nodes.Happyai.geometry}
            material={materials["Mat.2"]}
            position={[-3.247, 417.723, -69.856]}
          />
          <group name="Legs" position={[0, 28.32, -28.347]}>
            <skinnedMesh
              name="Legs_1"
              geometry={nodes.Legs_1.geometry}
              material={materials["Mat.1"]}
              skeleton={nodes.Legs_1.skeleton}
            />
          </group>
          <group
            name="Tail"
            position={[27.006, -74.689, -99.688]}
            rotation={[0, 0.735, 0]}
          >
            <skinnedMesh
              name="Tail_1"
              geometry={nodes.Tail_1.geometry}
              material={materials["Mat.1"]}
              skeleton={nodes.Tail_1.skeleton}
            />
          </group>
          <group name="Body" position={[-0.685, 10, -41.707]}>
            <primitive object={nodes.HappyHip_R} />
            <primitive object={nodes.HappyHip_L} />
            <primitive object={nodes.HappyTail} />
          </group>
          <mesh
            name="Body_1"
            castShadow
            receiveShadow
            geometry={nodes.Body_1.geometry}
            material={materials["Mat.1"]}
            position={[1.37, 10, -41.707]}
            scale={[0.9, 1.2, 1]}
          >
            <mesh
              name="Ear_L"
              castShadow
              receiveShadow
              geometry={nodes.Ear_L.geometry}
              material={materials["Mat.1"]}
              position={[34.08, 220.841, 0]}
              rotation={[0, 0, -0.087]}
            />
            <mesh
              name="Ear_R"
              castShadow
              receiveShadow
              geometry={nodes.Ear_R.geometry}
              material={materials["Mat.1"]}
              position={[-36.82, 220.841, 0]}
              rotation={[0, 0, 0.087]}
            />
            <mesh
              name="Mouth"
              castShadow
              receiveShadow
              geometry={nodes.Mouth.geometry}
              material={materials["Mat.2"]}
              position={[-0.197, 88.88, 106.717]}
              rotation={[-0.099, 0.017, 0.024]}
             > <meshStandardMaterial color={"#F5F5F5"}/></mesh>
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/RevisedV2/Happy.gltf");
