/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect,useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Happy.gltf");
  const { animations:animations2} = useGLTF("/models/Angry.gltf");
  const { actions,names } = useAnimations(animations, group);

 
  useEffect(()=>{
    console.log(actions)
    console.log(names)
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group  scale={0.01}>
        <mesh
          name="Happy_FBX"
          castShadow
          receiveShadow
          geometry={nodes.Happy_FBX.geometry}
          material={nodes.Happy_FBX.material}
          morphTargetDictionary={nodes.Happy_FBX.morphTargetDictionary}
          morphTargetInfluences={nodes.Happy_FBX.morphTargetInfluences}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Happy.gltf");
