/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
 
export function SadV2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/RevisedV2/Sad.gltf");
  const { actions,names } = useAnimations(animations, group);

  useEffect(()=>{
    console.log(actions)
    console.log(names)
    actions[names[0]].reset().fadeIn().play()
  },[])
  return (
    <group ref={group} {...props} dispose={null} scale={0.01}>
      <group>
        <group name="Sad" position={[0.913, -130, 1.608]}>
          <mesh
            name="Sadai"
            castShadow
            receiveShadow
            geometry={nodes.Sadai.geometry}
            material={materials["Mat.2"]}
            position={[-1.02, 350.835, -0.726]}
           >  <meshStandardMaterial color={"#F5F5F5"}/></mesh>
          <mesh
            name="Cloud"
            castShadow
            receiveShadow
            geometry={nodes.Cloud.geometry}
            material={materials["Mat.1"]}
            position={[5.445, 377.992, -53.409]}
            scale={100}
          />
          <mesh
            name="Particle1"
            castShadow
            receiveShadow
            geometry={nodes.Particle1.geometry}
            material={materials["Mat.1"]}
            position={[-17.741, 351.878, -52.086]}
          />
          <mesh
            name="Particle2"
            castShadow
            receiveShadow
            geometry={nodes.Particle2.geometry}
            material={materials["Mat.1"]}
            position={[15.291, 340.016, -52.086]}
            scale={0.939}
          />
          <mesh
            name="Particle3"
            castShadow
            receiveShadow
            geometry={nodes.Particle3.geometry}
            material={materials["Mat.1"]}
            position={[56.398, 351.878, -52.086]}
          />
          <mesh
            name="Particle4"
            castShadow
            receiveShadow
            geometry={nodes.Particle4.geometry}
            material={materials["Mat.1"]}
            position={[-71.327, 340.016, -52.086]}
            scale={0.939}
          />
          <mesh
            name="Particle5"
            castShadow
            receiveShadow
            geometry={nodes.Particle5.geometry}
            material={materials["Mat.1"]}
            position={[91.632, 351.878, -52.086]}
          />
          <mesh
            name="Particle"
            castShadow
            receiveShadow
            geometry={nodes.Particle.geometry}
            material={materials["Mat.1"]}
            position={[-41.231, 309.703, -52.086]}
            scale={0.784}
          />
          <group
            name="Tail"
            position={[-0.913, 144.93, -43.605]}
            rotation={[0, 0.735, 0]}
          >
            <skinnedMesh
              name="Tail_1"
              geometry={nodes.Tail_1.geometry}
              material={materials["Mat.1"]}
              skeleton={nodes.Tail_1.skeleton}
            />
          </group>
          <group name="Body" position={[-0.913, -2.163, -1.608]}>
            <primitive object={nodes.Joint1} />
            <primitive object={nodes.SadHip_L} />
            <primitive object={nodes.SadHip_R} />
          </group>
          <group name="SadLegs" position={[-0.228, 58.642, 3.216]}>
            <group name="Legs" position={[0, 6.855, 8.536]}>
              <skinnedMesh
                name="Legs_1"
                geometry={nodes.Legs_1.geometry}
                material={materials["Mat.1"]}
                skeleton={nodes.Legs_1.skeleton}
              />
            </group>
          </group>
          <mesh
            name="Body_1"
            castShadow
            receiveShadow
            geometry={nodes.Body_1.geometry}
            material={materials["Mat.1"]}
            position={[1.142, -47.163, -1.608]}
          >
            <mesh
              name="Mouth"
              castShadow
              receiveShadow
              geometry={nodes.Mouth.geometry}
              material={materials["Mat.2"]}
              position={[-2.055, 113.096, 127.227]}
             ><meshStandardMaterial color="white"/></mesh>
            <mesh
              name="Ear_L"
              castShadow
              receiveShadow
              geometry={nodes.Ear_L.geometry}
              material={materials["Mat.1"]}
              position={[98.671, 98.394, 0]}
            />
            <mesh
              name="Ear_R"
              castShadow
              receiveShadow
              geometry={nodes.Ear_R.geometry}
              material={materials["Mat.1"]}
              position={[-96.865, 98.394, 0]}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/RevisedV2/Sad.gltf");