/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function SurprisedV1(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Revised/Surprised.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null} scale={0.01} position={[0,-1.05,0]}>
      <group>
        <mesh
          name="Surprised"
          castShadow
          receiveShadow
          geometry={nodes.Surprised.geometry}
          material={materials["Mat.1"]}
          scale={80}
        >
          <group name="Sweep" position={[-0.001, 1.359, 0.005]} scale={0.013}>
            <mesh
              name="Sweep_1"
              castShadow
              receiveShadow
              geometry={nodes.Sweep_1.geometry}
              material={materials["Mat.1"]}
            /> 
          </group>
          <mesh
            name="Sweep_2"
            castShadow
            receiveShadow
            geometry={nodes.Sweep_2.geometry}
            material={materials["Mat.1"]}
            position={[-0.001, 1.359, 0.005]}
            scale={0.013}
          />
          <group
            name="Symmetry"
            position={[-0.001, 1.974, -0.447]}
            scale={0.013}
          >
            <mesh
              name="Symmetry_1"
              castShadow
              receiveShadow
              geometry={nodes.Symmetry_1.geometry}
              material={materials["Mat.1"]}
             ><meshToonMaterial/></mesh>
            <mesh
              name="Symmetry-Mat1"
              castShadow
              receiveShadow
              geometry={nodes["Symmetry-Mat1"].geometry}
              material={materials["Mat.1"]}
            />
          </group>
          <group
            name="Sweep_3"
            position={[-0.001, 1.714, 0.551]}
            rotation={[-0.282, 0, 0]}
            scale={0.013}
          >
            <mesh
              name="Sweep_4"
              castShadow
              receiveShadow
              geometry={nodes.Sweep_4.geometry}
              material={materials["Mat.1"]}
             ><meshToonMaterial/></mesh>
          </group>
          <meshStandardMaterial color={"grey"}/>
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Revised/Surprised.gltf");

 
