/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
 
export function SurprisedV2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/RevisedV2/Surprised.gltf");
  const { actions,names } = useAnimations(animations, group);

  useEffect(()=>{
    console.log(actions)
    console.log(names)
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])
  return (
    <group ref={group} {...props} dispose={null} scale={0.01}>
      <group>
        <group name="Surprised" position={[0.228, -95.887, 4.453]}>
          <mesh
            name="wowai"
            castShadow
            receiveShadow
            geometry={nodes.wowai.geometry}
            material={materials["Mat.2"]}
            position={[14.888, 428.016, -20.974]}
          />
          <group name="Body" position={[-0.228, 16.662, -4.453]}>
            <mesh
              name="Tail"
              castShadow
              receiveShadow
              geometry={nodes.Tail.geometry}
              material={materials["Mat.1"]}
              position={[0, 128.389, -41.997]}
              rotation={[0, 0.735, 0]}
            />
            <primitive object={nodes.SurprisedHip_R} />
            <primitive object={nodes.SurprisedHip_L} />
          </group>
          <group name="SurprisedLegs" position={[0.457, 25.774, 8.906]}>
            <skinnedMesh
              name="SurprisedLegs_1"
              geometry={nodes.SurprisedLegs_1.geometry}
              material={materials["Mat.1"]}
              skeleton={nodes.SurprisedLegs_1.skeleton}
            />
          </group>
          <mesh
            name="Body_1"
            castShadow
            receiveShadow
            geometry={nodes.Body_1.geometry}
            material={materials["Mat.1"]}
            position={[-0.228, 16.662, -4.453]}
          >
            <mesh
              name="Ears"
              castShadow
              receiveShadow
              geometry={nodes.Ears.geometry}
              material={materials["Mat.1"]}
              position={[-27.549, 183.157, 57.236]}
            />
            <mesh
              name="Eyes"
              castShadow
              receiveShadow
              geometry={nodes.Eyes.geometry}
              material={materials["Mat.2"]}
              position={[0, 123.284, 109.733]}
            ><meshStandardMaterial color={"#F5F5F5"} /></mesh>
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/RevisedV2/Surprised.gltf");
